CONFIG = {
    URL: "https://mhgray.github.io/LD52Phlip/main.html",
    INTROTEXT: "LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE LUDUM DARE "
}